<a href="https://colab.research.google.com/github/Kai-Kun-1/AI-ML-course/blob/main/module1_lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic Matrix Operations

## Print outputs in python

Use the `print()` command to display content of a variable in python. For example a message 'Hello Python' can be displayed as:

In [ ]:
print("Hello Python")

Hello Python


Displaying output of a variable and operation in python as follows:

In [ ]:
a=2
b=5
print("Value of a:",a)
print("Value of b: ", b)
print("Value of the operation, a+(2b) is:",a+(2*b))

Value of a: 2
Value of b:  5
Value of the operation, a+(2b) is: 12


## Reading a value to a variable in python
Use the funtion `input()`. For example :

In [ ]:
v=input("Enter the value:")
print(" The value read is:", v)

Enter the value:10
 The value read is: 10


## Reading a vector in `python`

In [ ]:
import numpy as np
v1=np.array([1,2,3])
v2=np.array([2,4,5])
a=2.3
print("The vector is: {}".format(v1))
print('The scalar product of {}  with {} is : {}'.format(v1,a,a*v1))
print('The linear combination of {} and {} is :{}'.format(v1,v2,a*v1+v2))

The vector is: [1 2 3]
The scalar product of [1 2 3]  with 2.3 is : [2.3 4.6 6.9]
The linear combination of [1 2 3] and [2 4 5] is :[ 4.3  8.6 11.9]


## Matrix operations in `python`

In [ ]:
M1=np.array([[1,2,3],[2,3,4],[4,5,6]])
M2=np.array([[3,2,1],[2,4,6],[5,6,7]])
print('Sum of matrices:\n',M1+M2)
print('Scalar product:\n',a*M1)
print('Element-wise product:\n',M1*M2)
print('Matrix Product\n',np.dot(M1,M2))

Sum of matrices:
 [[ 4  4  4]
 [ 4  7 10]
 [ 9 11 13]]
Scalar product:
 [[ 2.3  4.6  6.9]
 [ 4.6  6.9  9.2]
 [ 9.2 11.5 13.8]]
Element-wise product:
 [[ 3  4  3]
 [ 4 12 24]
 [20 30 42]]
Matrix Product
 [[22 28 34]
 [32 40 48]
 [52 64 76]]
